# Generated by Django 5.2.7 on 2026-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0002_plantillas_iniciales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantillanotificacion",
            name="canales_default",
            field=models.JSONField(
                default=list, help_text='Canales por defecto: ["in_app","email"].'
            ),
        ),
        migrations.AlterField(
            model_name="plantillanotificacion",
            name="cuerpo_txt",
            field=models.TextField(
                help_text='Soporta {context} con .format() — ej.: "Tu orden {codigo} fue asignada".'
            ),
        ),
    ]
