# Generated by Django 5.2.7 on 2025-10-16 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bateria",
            fields=[
                ("idbateria", models.AutoField(primary_key=True, serialize=False)),
                ("voltaje", models.FloatField(help_text="Voltaje VCA en V")),
                ("corriente", models.FloatField(help_text="Corriente en A")),
                ("temperatura", models.FloatField(help_text="Temperatura en °C")),
                (
                    "capacidad_bateria",
                    models.FloatField(help_text="Capacidad de la batería en kWh"),
                ),
                (
                    "porcentaje_carga",
                    models.FloatField(help_text="Porcentaje de carga en %"),
                ),
                (
                    "tiempo_restante",
                    models.FloatField(help_text="Tiempo restante en horas"),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "domicilio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baterias",
                        to="core.domicilio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bateria",
                "verbose_name_plural": "Baterias",
                "db_table": "bateria",
            },
        ),
        migrations.CreateModel(
            name="Consumo",
            fields=[
                ("idconsumo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "energia_consumida",
                    models.FloatField(help_text="Energía Consumida en kwH"),
                ),
                ("potencia", models.FloatField(help_text="Potencia en kW")),
                (
                    "fuente",
                    models.CharField(
                        choices=[("solar", "Solar"), ("electrica", "Electrica")],
                        default="electrica",
                        max_length=12,
                    ),
                ),
                (
                    "costo",
                    models.FloatField(
                        help_text="Costo en moneda local del kwH consumido"
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "domicilio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumos",
                        to="core.domicilio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumo",
                "verbose_name_plural": "Consumos",
                "db_table": "consumo",
                "ordering": ["-fecha"],
                "unique_together": {("domicilio", "fecha")},
            },
        ),
    ]
