# Generated by Django 5.2.7 on 2026-04-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfiltecnico",
            name="area_profesional",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="perfiltecnico",
            name="estudios",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="perfiltecnico",
            name="hoja_vida",
            field=models.FileField(
                blank=True, null=True, upload_to="tecnicos/hojas_vida/"
            ),
        ),
        migrations.AddField(
            model_name="perfiltecnico",
            name="resumen_profesional",
            field=models.TextField(blank=True),
        ),
    ]
