# Generated by Django 5.2.7 on 2026-04-29 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_instalacion_cliente_usuario_empresa_cliente_and_more"),
        ("tecnicos", "0002_perfiltecnico_area_profesional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfiltecnico",
            name="prestador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tecnicos",
                to="core.prestadorservicio",
            ),
        ),
    ]
