# Generated by Django 5.2.7 on 2026-04-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_instalacion_mantenimiento_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalacion",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Foto principal de la instalacion.",
                null=True,
                upload_to="instalaciones/",
            ),
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("idsensor", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=120)),
                ("codigo", models.CharField(max_length=64, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gateway", "Gateway"),
                            ("inversor", "Inversor"),
                            ("medidor", "Medidor"),
                            ("bateria", "Bateria"),
                            ("irradiancia", "Irradiancia"),
                            ("temperatura", "Temperatura"),
                            ("otro", "Otro"),
                        ],
                        default="medidor",
                        max_length=20,
                    ),
                ),
                ("unidad", models.CharField(blank=True, max_length=24)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("mantenimiento", "Mantenimiento"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("ultima_lectura", models.FloatField(blank=True, null=True)),
                ("fecha_ultima_lectura", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("creado_at", models.DateTimeField(auto_now_add=True)),
                ("actualizado_at", models.DateTimeField(auto_now=True)),
                (
                    "instalacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensores",
                        to="core.instalacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor",
                "verbose_name_plural": "Sensores",
                "db_table": "sensor",
                "ordering": ["instalacion__nombre", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["instalacion", "estado"], name="sensor_inst_estado"
                    ),
                    models.Index(fields=["codigo"], name="sensor_codigo_idx"),
                ],
            },
        ),
    ]
