# Generated by Django 5.2.7 on 2026-04-29 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_instalacion_imagen_sensor"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalacion",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instalaciones_cliente",
                to="core.empresa",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="empresa_cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_cliente",
                to="core.empresa",
            ),
        ),
        migrations.CreateModel(
            name="PrestadorServicio",
            fields=[
                ("idprestador", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                (
                    "nit",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "ciudad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestadores_servicio",
                        to="core.ciudad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestador de servicio",
                "verbose_name_plural": "Prestadores de servicio",
                "db_table": "prestador_servicio",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="instalacion",
            name="prestador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instalaciones",
                to="core.prestadorservicio",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="prestador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="core.prestadorservicio",
            ),
        ),
    ]
