# Generated by Django 5.2.7 on 2026-05-04 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_backfill_prestador_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarifa",
            fields=[
                ("idtarifa", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(
                        help_text="Etiqueta humana, p.ej. 'Bogotá - Estrato 4 - 2026 Q1'.",
                        max_length=120,
                    ),
                ),
                (
                    "valor_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo del kWh en moneda local (ej. COP).",
                        max_digits=10,
                    ),
                ),
                ("moneda", models.CharField(default="COP", max_length=8)),
                ("vigente_desde", models.DateTimeField()),
                ("vigente_hasta", models.DateTimeField(blank=True, null=True)),
                ("creado_at", models.DateTimeField(auto_now_add=True)),
                ("actualizado_at", models.DateTimeField(auto_now=True)),
                (
                    "ciudad",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si se define, aplica a todas las instalaciones de la ciudad.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="core.ciudad",
                    ),
                ),
                (
                    "instalacion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override puntual para una instalación.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="core.instalacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de energía",
                "verbose_name_plural": "Tarifas de energía",
                "db_table": "tarifa",
                "ordering": ["-vigente_desde", "-idtarifa"],
                "indexes": [
                    models.Index(
                        fields=["ciudad", "vigente_desde"],
                        name="idx_tarifa_ciudad_desde",
                    ),
                    models.Index(
                        fields=["instalacion", "vigente_desde"],
                        name="idx_tarifa_inst_desde",
                    ),
                ],
            },
        ),
    ]
